### ISSUE TITLE
First Alpha Milestones

### ISSUE THREAD

**Issue by adpking** [DevOnTheRocks/StickyChunk#1]
## Alpha Objectives 
Implementations to complete before the first alpha build is released.

- [x] Create a command for singular chunk loading.
- [x] Create a command for regional chunk loading.
- [ ] Verify database consistency and test other data storage implementations.
- [x] Create personal and world behaviours manually.
- [x] Create at least one configurable system for chunk restrictions.
- [x] Implement the new LoadingTicket Data API method.
- [x] Integrate with the Economy API.
