### ISSUE TITLE
Second Alpha Milestones

### ISSUE THREAD

**Issue by adpking** [DevOnTheRocks/StickyChunk#2]
## Alpha Two Objectives 
Implementations to complete before the second alpha build is released.

- [ ] Consolidate load commands into one class.
- [ ] Optionally use the Economy API to charge for chunks.
- [ ] Make region selector tool configurable.
- [ ] Refund tickets that exceed the callback maxTickets.
